//! Qdrant vector database client for storing and searching outfit embeddings
//!
//! Provides dual-vector storage (image + text) and ANN search using
//! cosine similarity.

use qdrant_client::Qdrant;
use qdrant_client::qdrant::{
    PointStruct, UpsertPointsBuilder, SearchPointsBuilder,
    Vectors, NamedVectors, Vector,
};
use std::collections::HashMap;

/// Client wrapper around a Qdrant collection that stores outfit embeddings.
///
/// Each point in the collection contains two named vectors (`"image"` and `"image"`)
/// plus a payload with `image_url`, `description` and `category`.
pub struct VectorDB {
    client: Qdrant,
    collection: String,
}

/// A single result returned from a vector similarity search.
pub struct SearchResult {
    /// Path to the outfit image on disk.
    pub image_url: String,
    /// VLM-generated caption or DeepFashion2 category label.
    pub description: String,
    /// Cosine similarity score between the query vector and this result.
    /// Ranges from `0.0` (unrelated) to `1.0` (identical).
    pub score: f32,
}

impl VectorDB {

    /// The constructor of the client wrapper.
    ///
    /// # Arguments
    ///
    /// * `url` thr url of your cluster.
    /// * `api_key` the api_key of your cluster.
    /// * `collection` the name of one of the collections of your cluster.
    ///
    /// # Returns
    ///
    /// A new database instance that holds your cluster database connection.
    pub fn new(url: &str, api_key: &str, collection: &str) -> Self {
        let client = Qdrant::from_url(url)
            .api_key(api_key)
            .build()
            .unwrap();
        Self { client, collection: collection.to_string(), }
    }


    /// Function to instert a photo or an image of an outfit or clothes to the
    /// database.
    ///
    /// # Arguments
    ///
    /// * `image_vector` The image vector generated by the AI model.
    /// * `text_vector` The text vector generated by the AI model.
    /// * `image_path` The path of the image in the file tree.
    /// * `description` A description of the image generated by VLM model.
    /// * `category` The category of the photo, I used DeepFashion2 as the dataset, so it contains a
    /// category field in its JSON, its used as a fallback when the description is not good.
    ///
    ///
    /// # Errors
    ///
    /// Returns an error if the Qdrant upsert request fails.
    pub async fn upsert_outfit(
        &self,
        image_vector: Vec<f32>,
        text_vector: Vec<f32>,
        image_path: &str,
        description: &str,
        category: &str,
    ) -> Result<(), Box<dyn std::error::Error>> {
        let named_vectors = NamedVectors {
            vectors: HashMap::from([
                ("image".to_string(), Vector::from(image_vector)),
                ("text".to_string(), Vector::from(text_vector)),
            ]),
        };

        let point = PointStruct::new(
            uuid::Uuid::new_v4().to_string(),
            Vectors::from(named_vectors),
            [
                ("image_url", image_path.into()),
                ("description", description.into()),
                ("category", category.into()),
            
            ],
        );

        self.client
            .upsert_points(UpsertPointsBuilder::new(&self.collection, vec![point]))
            .await?;

        Ok(())
    }

    /// Function to query the database given a text vector.
    ///
    /// # Arguments
    ///
    /// * `vector` The text vector to use as a query.
    /// * `limit` The limit of results the query can return.
    ///
    /// # Returns
    ///
    /// A list of the `limit` most similar outfits ordered by descending similarity score.
    pub async fn search_by_text_vector(
        &self,
        vector: Vec<f32>,
        limit: u64,
    ) -> Result<Vec<SearchResult>, Box<dyn std::error::Error>> {
        self.search_named("text", vector, limit).await
    }


    /// Function to query the database given an image vector.
    ///
    /// # Arguments
    ///
    /// * `vector` The image vector to use as a query.
    /// * `limit` The limit of results the query can return.
    ///
    /// # Returns
    ///
    /// A list of the `limit` most similar outfits ordered by descending similarity score.
    pub async fn search_by_image_vector(
        &self,
        vector: Vec<f32>,
        limit: u64,
    ) -> Result<Vec<SearchResult>, Box<dyn std::error::Error>> {
        self.search_named("image", vector, limit).await
    }


    /// Auxiliary function to query the database given a specific vector and its
    /// type.
    ///
    /// Performs an approximate nearest neighbor search against the named vector
    /// space in Qdrant using cosine similarity. This is done in QDRANT.
    ///
    /// # Arguments
    ///
    /// * `vector_name` The type of the vector (`image` or `text`)
    /// * `vector` The vector of the input image or text.
    /// * `limit` The limit of items that returns the query.
    ///
    /// # Returns
    ///
    /// Returns an Ok() type that holds the results of the given query.
    ///
    /// # Errors
    ///
    /// Returns an error if the Qdrant query fails.
    async fn search_named(
        &self,
        vector_name: &str,
        vector: Vec<f32>,
        limit: u64,
    ) -> Result<Vec<SearchResult>, Box<dyn std::error::Error>> {
        let search_result = self.client
            .search_points(
                SearchPointsBuilder::new(&self.collection, vector, limit)
                    .vector_name(vector_name)
                    .with_payload(true)
            )
            .await?;

        let results = search_result.result
            .into_iter()
            .filter_map(|point| {
                let get_str = |key: &str| {
                    point.payload.get(key)
                        .and_then(|v| v.kind.as_ref())
                        .and_then(|k| {
                            if let qdrant_client::qdrant::value::Kind::StringValue(s) = k {
                                Some(s.clone())
                            } else {
                                None
                            }
                        })
                };

                Some(SearchResult {
                    image_url: get_str("image_url")?,
                    description: get_str("description").unwrap_or_default(),
                    score: point.score,
                })
            })
            .collect();
        
        Ok(results)
    }
}
